### PR TITLE
Report major breaking change type in JSON report and support pub refs without version

### LINKED ISSUE #186: JSON report should properly contain "major" as change type for breaking changes
**Describe the bug**
Widening the return type is treated as minor change but can break consumer code

update: The problem is the JSON report that does not contain "major" in the change type field.

**To Reproduce**

https://github.com/dart-lang/ecosystem/issues/304#issuecomment-2402818324

**Actual and Expected behavior**
the type field contains "minor" as it is only populated for non breaking changes

### LINKED ISSUE #188: Get latest version by default in `diff` command
As the `version` argument in [`dart pub cache`](https://dart.dev/tools/pub/cmd/pub-cache) is optional, it would be nice to have this reflected in [the code](https://github.com/bmw-tech/dart_apitool/blob/04e6ec780b240b91fff52a99f96e3e20d768f33b/lib/src/tooling/pub_interaction.dart#L23). This would allow for getting the latest version by specifying only the package in the diff command, e.g. `diff --old pub://package_name`.

### PR DESCRIPTION
**Pull request by devmil**
## Description
This PR fixes the JSON report to specify "major" breaking changes in the type field in the JSON report and it adds support for omitting the version in pub refs. In that case dart_apitool will install the package without version constraints using pub and afterwards just use the latest version available in the cache.

## Type of Change
- [x] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

Fixes #188 
Fixes #186

### CODE REVIEW

File: lib/src/tooling/pub_interaction.dart [hunk 1]
```diff
@@ -56,8 +65,52 @@ abstract class PubInteraction {
...
 
+  static Version getLatestVersionInCacheFor(String packageName) {
+    final allVersions = getAllPackageVersionsForPackageInCache(packageName);
+    final versions = allVersions.keys.toList(growable: false);
+    if (versions.isEmpty) {
+      throw RunDartError('No version of $packageName found');
+    }
+
+    versions.sort();
+    return versions.last;
```
[the remark this answers is not in the document]
Comment (devmil) [reply lib/src/tooling/pub_interaction.dart:76]: nice!

File: test/integration_tests/cli/diff_command_test.dart [hunk 2]
```diff
@@ -143,5 +143,25 @@ void main() {
       },
       timeout: integrationTestTimeout,
     );
+
+    test(
+      'diffing cloud_firestore 4.3.1 to latest works',
+      () async {
+        // just some random package for testing the diff command for pub refs without version
```
Comment (marafelismino) [inline test/integration_tests/cli/diff_command_test.dart:150]: I saw that we are repeating ourselves with this comment of 'just some random package ...'. What do you think about adding this comment at the top of the test file instead of repeating it for every test? I know that it will (probably) be harder to understand where the package came from but I don't think that repeating it for all the tests is much better too :/

File: test/unit_tests/diff/report/json_diff_reporter_test.dart [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+      expect(reporter, isA<JsonDiffReporter>());
+    });
+
+    test('Can handle empty diff report', () async {
+      final diffResult = createEmptyDiffResult();
+      await reporter.generateReport(diffResult, anyVersionCheckResult);
+      final jsonReport = jsonDecode(collectedFileContent.toString());
+      expect(jsonReport['report']['noChangesDetected'], isTrue);
+    });
+    test('Can handle diff report with only one breaking change', () async {
```
Comment (marafelismino) [inline test/unit_tests/diff/report/json_diff_reporter_test.dart:84]:
```suggestion
    });
    
    test('Can handle diff report with only one breaking change', () async {
```
same for the other ones below if you agree with it

File: test/unit_tests/diff/report/json_diff_reporter_test.dart [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+      final diffResult = createEmptyDiffResult();
+      addBreakingChange(diffResult, changeCode: ApiChangeCode.ci01);
+      await reporter.generateReport(diffResult, anyVersionCheckResult);
+      final jsonReport = jsonDecode(collectedFileContent.toString());
+      expect(jsonReport['report']['breakingChanges'], isNotNull);
```
Comment (marafelismino) [inline test/unit_tests/diff/report/json_diff_reporter_test.dart:89]:
```suggestion
      expect(jsonReport['report']['breakingChanges'], isNotNull);
```
I would create a method to return the breaking changes property and another one to get the 'children' of it. Otherwise, if we need to change the name of any of it, we would need to adapt a lot of tests

**Review by fabiomcarneiro — APPROVED** [review]
