### PR TITLE
fix: narrowing return type should not be breaking

### LINKED ISSUE #221: Restricting the type of a return should not be a breaking change
**Describe the bug**
Similar to https://github.com/bmw-tech/dart_apitool/issues/123. If you had an `Iterable<int>` as a getter/method result and there was a change to `List<int>`, or even `List<num>` to `List<int>` (changing the type parameters to be more specific) this should not be considered breaking. Since the new value is assignable to the old one and any user code would still be valid.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
For https://github.com/FMorschel/due_date/tree/exports-and-tests branch compared with the pub https://pub.dev/packages/due_date 2.2.2 version. In this case, the results are classes from this package, but this is easily reproducible with the cases I wrote above.

**Actual and Expected behavior**
For those to be considered minor.

**System info (please complete the following information):**
 - Dart SDK version: 3.9.0-edge.d3c323e26d1663ab422ff89b65d5a78b0e89c997 (main) (Sun Jul 6 22:55:04 2025 -0700) on "windows_x64"
 - dart_apitool version 0.21.1

### PR DESCRIPTION
**Pull request by devmil**
## Description
This PR is based on #222 
This PR fixes #221 

In this PR the TypeHierarchy that dart_apitool tracks gets extended to also understand generic types and their covariance.
This fixes return type change checks that led to breaking changes too fast (e.g. Iterable<num> -> List<int>)

## Type of Change
- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

### CODE REVIEW

File: test/integration_tests/diff/test_package_return_type_changes_test.dart [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+            packagePath: path.join(
+          'test',
+          'test_packages',
+          'return_type_changes',
+          'package_with_narrow_returns',
+        ));
+      },
+    );
+
+    group('return type narrowing (should be non-breaking)', () {
```
Comment (adamgic) [inline test/integration_tests/diff/test_package_return_type_changes_test.dart:29]: Would the following changes of return type be considered non-breaking?
`List<String?>` to `List<String>`
`Map<String, dynamic>`  to `Map<String, String>`
`dynamic` to `int`

Comment (devmil) [reply test/integration_tests/diff/test_package_return_type_changes_test.dart:29]: added some more tests to cover those cases and fixed dart_apitool to behave correctly

**Review by adamgic — APPROVED** [review]
