### PR TITLE
fix: remove dependency_overrides from temporary pubspec.yaml

### LINKED ISSUE #198: Relative paths seem to not be supported
**Describe the bug**
While trying out the PR health workflow in dart-lang/native, I saw that it throws for some of the packages in that monorepo.

**To Reproduce**
```
#git clone dart-lang/native
cd native/
flutter pub global run dart_apitool:main diff --no-check-sdk-version --old pub://ffigen --new pkgs/ffigen --report-format json --report-file-path report.json
```
**Actual and Expected behavior**
Throws an error
```
Error: Exception: Because ffigen depends on objective_c from path which doesn't exist (could not find package objective_c at "../objective_c"), version solving failed.
```
But this package does exist there. Probably some copying doesn't copy the path dependencies?

**System info (please complete the following information):**
 - Output of `dart --version`: `Dart SDK version: 3.7.0-207.0.dev (dev) (Mon Dec 2 12:02:22 2024 -0800) on "linux_x64"`
 - dart_apitool version (`dart-apitool --version`): `0.20.0`

**Additional context**
-

### PR DESCRIPTION
**Pull request by devmil**
## Description
dart_apitool has issues with packages that contain dependency_overrides in their pubspec.yaml and are pulled from pub.
Background:
Packages from pub get downloaded to the pub cache and get copied into a temporary directory to do local adaptions and preparations.
Some packages, especially ones from a mono repository, contain dependency overrides that point to relative paths. Those paths are not valid if you look at this package in isolation and pub get run on that package copy fails as it is not able to resolve those relative path overrides.
To avoid this situation dart_apitool now removed dependency overrides on that local copy (to use the variant of dependencies that would be used transitively anyways)

## Type of Change
- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

Fixes #198

### CODE REVIEW

File: lib/src/cli/commands/command_mixin.dart [hunk 1]
```diff
@@ -175,6 +176,25 @@ OBSOLETE: Has no effect anymore.
       await Directory(exampleDirPath).delete(recursive: true);
     }
 
+    // remove any dependency overrides from the pubspec.yaml
+    final pubspecFile = File(p.join(packagePath, 'pubspec.yaml'));
+    if (pubspecFile.existsSync()) {
+      try {
+        final pubSpec = PubSpec.load(directory: packagePath);
+        // removeAll of dependencyOverrides has an issue in the current version of pubspec_manager
```
Comment (adamgic) [inline lib/src/cli/commands/command_mixin.dart:184]:
```suggestion
        // removeAll of dependencyOverrides, there's an issue in the current version of pubspec_manager
```

File: lib/src/cli/commands/command_mixin.dart [hunk 2]
```diff
@@ -175,6 +176,25 @@ OBSOLETE: Has no effect anymore.
...
+        // as it doesn't remove the section part of the dependency overrides and therefore are not removed
```
Comment (adamgic) [inline lib/src/cli/commands/command_mixin.dart:185]:
```suggestion
        // as it doesn't remove the section part of the dependency overrides and therefore it is not removed
```

**Review by adamgic — APPROVED** [review]
