### PR TITLE
fix!: widening parameter types is non breaking

### LINKED ISSUE #123: widening the type of a parameter should not be a breaking change
**Describe the bug**
If an executable gets its parameter changed in a way that the old parameter type is still covered by the new parameter type this change should not be breaking.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
- Version1: doSomething(String parameter)
- Version2: doSomething(String? parameter)

**Actual and Expected behavior**
If the client code is still valid because the new type is covering the old type then this should not be a breaking change

**System info (please complete the following information):**
 - dart_apitool version 0.13.0

### PR DESCRIPTION
**Pull request by devmil**
## Description
This PR adds tracking of the type hierarchy while analyzing and uses that information to make a better decision about whether a type change of a parameter is breaking or not.
If the type got widened (so old type is assignable to the new type) then the change is considered non-breaking.

Fixes #123 

## Type of Change

- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [x] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

### CODE REVIEW

**Review by robert-northmind — APPROVED** [review]

**Review by klink182 — APPROVED** [review]

File: lib/src/analyze/api_relevant_elements_collector.dart [hunk 1]
```diff
@@ -114,15 +99,19 @@ class APIRelevantElementsCollector extends RecursiveElementVisitor<void> {
...
       //create new collector with the used type as an exception from the public element restrictions
       final collector = APIRelevantElementsCollector(
         privateElementExceptions: [directElement.id],
         // pass on the already collected elements to make sure that we don't collect elements twice even if we are going down the usage tree
         collectedElementIds: _collectedElementIds,
-        namespace:
-            _getNamespaceForLibrary(directElementLibrary, referringElement),
+        typeHierarchy: typeHierarchy,
+        namespace: InternalDeclarationUtils.getNamespaceForElement(
+            type.element2, referringElement),
```
Comment (adamgic) [inline lib/src/analyze/api_relevant_elements_collector.dart:114]:
```suggestion
            directElement, referringElement),
```

**Review by adamgic — APPROVED** [review]
