### PR TITLE
fixes interface equality logic for the differ

### LINKED ISSUE #167: Renaming a file should not detect a breaking change
I moved interface `CreateMatchers` from file `a.dart` to `b.dart`. The tool detected a breaking change

```
BREAKING CHANGES
└── Interface "CreateMatchers" removed (CI01)
Non-Breaking changestilities 0.5.0 (0.8.0 available)
├── Interface "CreateMatchers" added (CI02) (minor)
```

Expected result:

no diff, the interface was moved, neither added nor deleted.

### PR DESCRIPTION
**Pull request by devmil**
## Description
This PR changes the logic that checks for interface equality in two package models to account for situations that renamed the library of an interface without touching the entry point and hence don't lead to a public API change

## Type of Change

- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

fixes #167

### CODE REVIEW

File: lib/src/diff/package_api_differ.dart [hunk 1]
```diff
@@ -105,11 +105,31 @@ class PackageApiDiffer {
...
+
+        // we need to do additional checks as we might have naming conflicts otherwise
+
+        // if the entry points are the same, then we can assume that the interfaces are the same (independent of their relative path)
+        if (SetEquality<String>()
+            .equals(oldInterface.entryPoints, newInterface.entryPoints)) {
+          return true;
+        }
+
+        // here the name is equal but we have different entry points.
```
Comment (adamgic) [inline lib/src/diff/package_api_differ.dart:122]:
```suggestion
        // here the name is equal, but we have different entry points
```

**Review by adamgic — APPROVED** [review]
